//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_ProductionToday
    {
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public string workShift { get; set; }
        public Nullable<int> AppLL { get; set; }
        public Nullable<System.DateTime> AppLLdate { get; set; }
        public Nullable<int> AppTL { get; set; }
        public Nullable<System.DateTime> AppTLdate { get; set; }
        public Nullable<int> AppAM { get; set; }
        public Nullable<System.DateTime> AppAMdate { get; set; }
    }
}
