//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_ManPowersTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp_ManPowersTable()
        {
            this.Emp_AuthorizationTable = new HashSet<Emp_AuthorizationTable>();
            this.Emp_ManPowerRegistedTable = new HashSet<Emp_ManPowerRegistedTable>();
            this.Emp_SectionMemberTable = new HashSet<Emp_SectionMemberTable>();
            this.Emp_UserLoginTable = new HashSet<Emp_UserLoginTable>();
            this.Emp_UserLoginTrackingTable = new HashSet<Emp_UserLoginTrackingTable>();
            this.Software_ErrorCodeTable = new HashSet<Software_ErrorCodeTable>();
        }
    
        public int run { get; set; }
        public int userID { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string grade { get; set; }
        public int roles { get; set; }
        public string divisionID { get; set; }
        public string plantID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_AuthorizationTable> Emp_AuthorizationTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_ManPowerRegistedTable> Emp_ManPowerRegistedTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_SectionMemberTable> Emp_SectionMemberTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_UserLoginTable> Emp_UserLoginTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_UserLoginTrackingTable> Emp_UserLoginTrackingTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Software_ErrorCodeTable> Software_ErrorCodeTable { get; set; }
    }
}
