//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_ManPowerRegistedTable
    {
        public int run { get; set; }
        public System.DateTime registDate { get; set; }
        public int userID { get; set; }
        public string sectionCode { get; set; }
        public string workType { get; set; }
        public string DayNight { get; set; }
        public string shiftAB { get; set; }
        public int functionID { get; set; }
        public double rate { get; set; }
        public double period { get; set; }
        public int functionOtID { get; set; }
        public double rateOT { get; set; }
        public double periodOT { get; set; }
        public string DecInc { get; set; }
        public string sectionCodeFrom { get; set; }
    
        public virtual Emp_ManPowersTable Emp_ManPowersTable { get; set; }
        public virtual Emp_MPFunctionTable Emp_MPFunctionTable { get; set; }
        public virtual Emp_MPFunctionTable Emp_MPFunctionTable1 { get; set; }
    }
}
