//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_UserLoginTable
    {
        public int run { get; set; }
        public Nullable<int> userID { get; set; }
        public byte[] userPassword { get; set; }
        public Nullable<System.DateTime> userCreatedDate { get; set; }
        public Nullable<System.DateTime> userModifyDate { get; set; }
    
        public virtual Emp_ManPowersTable Emp_ManPowersTable { get; set; }
    }
}
