//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_SectionMemberTable
    {
        public int run { get; set; }
        public string sectionCode { get; set; }
        public int userID { get; set; }
        public string shiftAB { get; set; }
        public Nullable<int> functionID { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> functionOtID { get; set; }
        public Nullable<double> rateOt { get; set; }
        public Nullable<System.DateTime> latestUpdate { get; set; }
        public string divisionID { get; set; }
        public string plantID { get; set; }
    
        public virtual Emp_ManPowersTable Emp_ManPowersTable { get; set; }
        public virtual Emp_MPFunctionTable Emp_MPFunctionTable { get; set; }
        public virtual Emp_MPFunctionTable Emp_MPFunctionTable1 { get; set; }
    }
}
