//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_MPFunctionTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp_MPFunctionTable()
        {
            this.Emp_ManPowerRegistedTable = new HashSet<Emp_ManPowerRegistedTable>();
            this.Emp_ManPowerRegistedTable1 = new HashSet<Emp_ManPowerRegistedTable>();
            this.Emp_SectionMemberTable = new HashSet<Emp_SectionMemberTable>();
            this.Emp_SectionMemberTable1 = new HashSet<Emp_SectionMemberTable>();
        }
    
        public int functionID { get; set; }
        public string functionName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_ManPowerRegistedTable> Emp_ManPowerRegistedTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_ManPowerRegistedTable> Emp_ManPowerRegistedTable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_SectionMemberTable> Emp_SectionMemberTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_SectionMemberTable> Emp_SectionMemberTable1 { get; set; }
    }
}
