//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exclusion_RecordTable
    {
        public int run { get; set; }
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public string shiftAB { get; set; }
        public string workStyle { get; set; }
        public string exclusionID { get; set; }
        public int MP { get; set; }
        public double minute { get; set; }
        public double totalMH { get; set; }
        public Nullable<System.DateTime> recordTime { get; set; }
        public string decription { get; set; }
        public string divisionId { get; set; }
        public string plantId { get; set; }
    
        public virtual Exclusion_ItemsTable Exclusion_ItemsTable { get; set; }
    }
}
