//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class exclusionRecord
    {
        public int id { get; set; }
        public string section_id { get; set; }
        public System.DateTime regist_date { get; set; }
        public System.DateTime regist_datetime { get; set; }
        public string work_shift { get; set; }
        public string exclusion_id { get; set; }
        public double manpower { get; set; }
        public double period_secord { get; set; }
        public double total_manhour { get; set; }
        public string decription { get; set; }
    }
}
