//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loss_ItemsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loss_ItemsTable()
        {
            this.Loss_DetailTable = new HashSet<Loss_DetailTable>();
            this.Loss_SixRelatedTable = new HashSet<Loss_SixRelatedTable>();
        }
    
        public int run { get; set; }
        public string lossID { get; set; }
        public string lossName { get; set; }
        public Nullable<short> sort { get; set; }
        public string divisionID { get; set; }
        public string plantID { get; set; }
        public Nullable<System.DateTime> recordDate { get; set; }
        public Nullable<int> recordPersonID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loss_DetailTable> Loss_DetailTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loss_SixRelatedTable> Loss_SixRelatedTable { get; set; }
    }
}
