//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loss_RecordTable
    {
        public int run { get; set; }
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public string shiftAB { get; set; }
        public string lossID { get; set; }
        public int lossDetailID { get; set; }
        public System.DateTime dateTimeStart { get; set; }
        public System.DateTime dateTimeEnd { get; set; }
        public Nullable<double> Second { get; set; }
        public Nullable<short> MP { get; set; }
        public Nullable<double> totalMS { get; set; }
        public string partNumberStart { get; set; }
        public string partNumberEnd { get; set; }
        public string MCNumber { get; set; }
        public string errorCode { get; set; }
        public string divisionId { get; set; }
        public string plantId { get; set; }
        public string mcStop { get; set; }
        public Nullable<double> Pureloss { get; set; }
    }
}
