//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loss_DetailTable
    {
        public string lossID { get; set; }
        public int lossDetailID { get; set; }
        public string lossDetailName { get; set; }
        public string sectionCode { get; set; }
        public string divisionId { get; set; }
        public string plantId { get; set; }
        public Nullable<int> recodeId { get; set; }
        public string machineId { get; set; }
    
        public virtual Loss_ItemsTable Loss_ItemsTable { get; set; }
    }
}
