//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loss_SixRelatedTable
    {
        public int run { get; set; }
        public Nullable<short> sixGroupID { get; set; }
        public string lossID { get; set; }
        public string divisionId { get; set; }
        public string plantId { get; set; }
    
        public virtual Loss_ItemsTable Loss_ItemsTable { get; set; }
        public virtual Loss_SixGroupTable Loss_SixGroupTable { get; set; }
    }
}
