//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class machineList
    {
        public string id_section { get; set; }
        public string id_machine { get; set; }
        public string machine_name { get; set; }
        public int sort { get; set; }
        public string station_number { get; set; }
        public bool oee_used { get; set; }
        public Nullable<bool> production_end { get; set; }
    }
}
