//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class machineFaultCode
    {
        public string section_id { get; set; }
        public string machine_id { get; set; }
        public string fault_code { get; set; }
        public string alarm_message { get; set; }
        public string decription { get; set; }
    }
}
