//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class manPower
    {
        public string user_id { get; set; }
        public string full_name { get; set; }
        public int role { get; set; }
        public string grade { get; set; }
        public string division_id { get; set; }
        public string plant_id { get; set; }
    }
}
