//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ML_NagaraStartTimeTable
    {
        public int run { get; set; }
        public string SectionCode { get; set; }
        public Nullable<System.DateTime> RegistDate { get; set; }
        public string DayNight { get; set; }
        public string StationNo { get; set; }
        public Nullable<System.DateTime> RegistDateTime { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> NagaraSWTime { get; set; }
    }
}
