//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ML_RecordTable
    {
        public int run { get; set; }
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public System.DateTime registDateTime { get; set; }
        public string partNumber { get; set; }
        public double mcTimeSec { get; set; }
        public string mcNumber { get; set; }
        public string OKNG { get; set; }
        public Nullable<double> htTimeSec { get; set; }
        public Nullable<double> CTTimeSec { get; set; }
    }
}
