//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WGREntities : DbContext
    {
        public WGREntities()
            : base("name=WGREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RD_HL_CalibrationTable> RD_HL_CalibrationTable { get; set; }
        public virtual DbSet<RD_PackingSlipTable> RD_PackingSlipTable { get; set; }
    }
}
