//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class oeeHistory
    {
        public int id { get; set; }
        public string section_id { get; set; }
        public System.DateTime regist_date { get; set; }
        public string machine_id { get; set; }
        public int type { get; set; }
        public int start_minute_time { get; set; }
        public int occure_period_minute { get; set; }
    }
}
