//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class oeeMachine
    {
        public string section_id { get; set; }
        public System.DateTime regist_date { get; set; }
        public string machine_id { get; set; }
        public double loading_time { get; set; }
        public double a1 { get; set; }
        public double a2 { get; set; }
        public double a3 { get; set; }
        public double a4 { get; set; }
        public double a5 { get; set; }
        public double a6 { get; set; }
        public double a7 { get; set; }
        public double a8 { get; set; }
        public double a9 { get; set; }
        public Nullable<double> a10 { get; set; }
        public double p1 { get; set; }
        public double p2 { get; set; }
        public double p3 { get; set; }
        public double p4 { get; set; }
        public Nullable<double> p5 { get; set; }
        public Nullable<double> p6 { get; set; }
        public Nullable<double> q1 { get; set; }
        public Nullable<double> q2 { get; set; }
        public double ok { get; set; }
        public double no_good { get; set; }
        public double re_work { get; set; }
        public double availability { get; set; }
        public double performance { get; set; }
        public double quality { get; set; }
        public double oee_summary { get; set; }
        public Nullable<double> oee_denso { get; set; }
        public Nullable<double> unknow { get; set; }
    }
}
