//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class orHistory
    {
        public int id { get; set; }
        public string section_id { get; set; }
        public System.DateTime regist_date { get; set; }
        public System.DateTime regist_date_time { get; set; }
        public double takt_time { get; set; }
        public double weight_time { get; set; }
        public double or_takt { get; set; }
        public double or_weight { get; set; }
        public double oee { get; set; }
    }
}
