//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pg_MH
    {
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public double MHNormal { get; set; }
        public double MHOT { get; set; }
        public double TotalMH { get; set; }
        public double exclusionHr { get; set; }
        public double GMH { get; set; }
    }
}
