//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_StdMonthlyTable
    {
        public int run { get; set; }
        public string sectionCode { get; set; }
        public string registYear { get; set; }
        public string registMonth { get; set; }
        public Nullable<int> productvolumn { get; set; }
        public Nullable<double> numberWorkDay { get; set; }
        public Nullable<short> numberShift { get; set; }
        public Nullable<double> manPower { get; set; }
        public Nullable<double> CycleTimeAverage { get; set; }
        public Nullable<double> stdRaio { get; set; }
    }
}
