//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class productionTodayApproval
    {
        public string section_id { get; set; }
        public System.DateTime regist_date { get; set; }
        public string work_shift { get; set; }
        public string ll_approval { get; set; }
        public string tl_approval { get; set; }
        public string mgr_approval { get; set; }
        public System.DateTime ll_approved_at { get; set; }
        public Nullable<System.DateTime> tl_approved_at { get; set; }
        public Nullable<System.DateTime> mgr_approved_at { get; set; }
    }
}
