//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_MachineFaultCodeTable
    {
        public int run { get; set; }
        public string sectionCode { get; set; }
        public string machineId { get; set; }
        public short faultCode { get; set; }
        public string messageAlarm { get; set; }
        public string decription { get; set; }
    }
}
