//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_ProgressResultTable
    {
        public int run { get; set; }
        public string sectionCode { get; set; }
        public string registYear { get; set; }
        public string registMonth { get; set; }
        public System.DateTime registDate { get; set; }
        public Nullable<short> workingDay { get; set; }
        public Nullable<int> post { get; set; }
        public Nullable<int> actualProduction { get; set; }
        public Nullable<int> actualProductionAcc { get; set; }
        public Nullable<int> productionBalance { get; set; }
        public Nullable<double> MHormal { get; set; }
        public Nullable<double> MHOT { get; set; }
        public Nullable<double> totalMH { get; set; }
        public Nullable<double> exclusionTime { get; set; }
        public Nullable<double> grossMH { get; set; }
        public Nullable<double> loss { get; set; }
        public Nullable<double> grossMHacc { get; set; }
        public Nullable<double> STDMH { get; set; }
        public Nullable<double> STDMHacc { get; set; }
        public Nullable<double> MR_MRG { get; set; }
        public Nullable<double> MR_TL { get; set; }
        public Nullable<double> MRTLacc { get; set; }
        public string Judge { get; set; }
    }
}
