//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class productionRecord
    {
        public int id { get; set; }
        public string id_section { get; set; }
        public System.DateTime regist_date { get; set; }
        public System.DateTime current_datetime { get; set; }
        public string part_number { get; set; }
        public string id_machine { get; set; }
        public string judge { get; set; }
        public double machine_time { get; set; }
        public double hand_time { get; set; }
        public double cycle_time { get; set; }
    }
}
