//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_TimeBreakQueueTable
    {
        public string sectionCode { get; set; }
        public string registYear { get; set; }
        public string registMonth { get; set; }
        public int breakQueue { get; set; }
        public string divisionID { get; set; }
        public string plantID { get; set; }
    }
}
