//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_PPASTable
    {
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public string dayNight { get; set; }
        public short hour { get; set; }
        public string monitor { get; set; }
        public Nullable<short> period { get; set; }
        public Nullable<short> plan100 { get; set; }
        public Nullable<short> accPlan { get; set; }
        public Nullable<short> volume { get; set; }
        public Nullable<short> accVol { get; set; }
        public Nullable<double> percentOA { get; set; }
        public Nullable<double> stdOA { get; set; }
        public string redAlarm { get; set; }
        public Nullable<double> percentOAavg { get; set; }
        public string workStatus { get; set; }
        public Nullable<short> volumePerHr { get; set; }
        public string alarm { get; set; }
    }
}
