//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_StdWorkingDayTable
    {
        public int run { get; set; }
        public string densoCustomer { get; set; }
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public Nullable<short> workHoliday { get; set; }
        public string divisionID { get; set; }
        public string plantID { get; set; }
    }
}
