//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_ProductionToday
    {
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public string workShift { get; set; }
        public string partNumber { get; set; }
        public int Qty { get; set; }
        public string dayNight { get; set; }
    }
}
