//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class progressSTDMH
    {
        public string section_id { get; set; }
        public System.DateTime regist_date { get; set; }
        public string work_shift { get; set; }
        public double std_mh { get; set; }
        public double production_volume { get; set; }
    }
}
