//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class progressMH
    {
        public string section_id { get; set; }
        public System.DateTime regist_date { get; set; }
        public double mh_normal { get; set; }
        public double mh_overtime { get; set; }
        public double mh_total { get; set; }
        public double exclusion_hour { get; set; }
        public double gross_mh { get; set; }
    }
}
