//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class progressProduction
    {
        public string section_id { get; set; }
        public System.DateTime regist_date { get; set; }
        public double post_plan_acc { get; set; }
        public double actual_production { get; set; }
        public double actual_production_acc { get; set; }
        public double production_balance { get; set; }
        public double mh_normal { get; set; }
        public double mh_ot { get; set; }
        public double mh_total { get; set; }
        public double exclusion_time { get; set; }
        public double mh_gross { get; set; }
        public double mh_gross_acc { get; set; }
        public double loss_time { get; set; }
        public double std_mh { get; set; }
        public double std_mh_acc { get; set; }
        public double mh_reduce_mgr { get; set; }
        public double mh_reduce_tl { get; set; }
        public double mh_reduce_tl_acc { get; set; }
        public double mh_reduce_mgr_acc { get; set; }
        public double mh_reduce_target { get; set; }
        public string judge { get; set; }
        public int working_day { get; set; }
    }
}
