//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RD_HL_CalibrationTable
    {
        public int run { get; set; }
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public System.DateTime currentDateTime { get; set; }
        public string dayNight { get; set; }
        public string machineId { get; set; }
        public short chamber { get; set; }
        public double firstBG { get; set; }
        public double secondBG { get; set; }
        public double firstSG { get; set; }
        public double secondSG { get; set; }
        public double judgeSN { get; set; }
        public double safetyFactor { get; set; }
        public double NGSetPoint { get; set; }
        public string calibrationCompleted { get; set; }
        public Nullable<int> AckPerson { get; set; }
        public Nullable<System.DateTime> AckDateTime { get; set; }
    }
}
