//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicePreparation
    {
        public string section_id { get; set; }
        public Nullable<bool> ppas { get; set; }
        public Nullable<bool> progress { get; set; }
        public Nullable<bool> oee { get; set; }
    }
}
