//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software_ErrorCodeTable
    {
        public int run { get; set; }
        public Nullable<System.DateTime> occuredDateTime { get; set; }
        public Nullable<int> userId { get; set; }
        public string errorCode { get; set; }
        public string functionName { get; set; }
        public string decription { get; set; }
    
        public virtual Emp_ManPowersTable Emp_ManPowersTable { get; set; }
    }
}
