//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software_RevisionTable
    {
        public System.DateTime registDate { get; set; }
        public string revisionNo { get; set; }
        public string authorize { get; set; }
        public string reason { get; set; }
        public string appName { get; set; }
    }
}
