//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class standardYearly
    {
        public string id_section { get; set; }
        public System.DateTime regist_date { get; set; }
        public double cycle_time_avg { get; set; }
        public double standard_ratio { get; set; }
        public float operation_ratio { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public string create_who { get; set; }
    }
}
