//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class standardNetTime
    {
        public string section_id { get; set; }
        public int regist_year { get; set; }
        public string part_number { get; set; }
        public double net_time { get; set; }
        public float cycle_time { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
    }
}
