//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeBreak
    {
        public string id_division { get; set; }
        public string id_plant { get; set; }
        public int break_no { get; set; }
        public int hour_no { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime stop_time { get; set; }
        public string monitor { get; set; }
        public int period { get; set; }
        public string day_night { get; set; }
        public System.DateTime start_time_monitor { get; set; }
        public System.DateTime stop_time_monitor { get; set; }
    }
}
