//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class todayWork
    {
        public string id_section { get; set; }
        public System.DateTime regist_date { get; set; }
        public string day_night { get; set; }
        public int work_hour { get; set; }
        public string work_shift { get; set; }
        public int break_no { get; set; }
    }
}
