//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> paid { get; set; }
        public Nullable<double> change { get; set; }
        public string payment_type { get; set; }
        public string payment_detail { get; set; }
        public string order_list { get; set; }
        public string staff_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
