//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class userLoginHistory
    {
        public string id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> login_at { get; set; }
        public Nullable<System.DateTime> logout_at { get; set; }
    }
}
