//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class XlossRecord
    {
        public int id { get; set; }
        public string section_id { get; set; }
        public System.DateTime regist_date { get; set; }
        public string work_shift { get; set; }
        public string loss_id { get; set; }
        public string loss_detail_id { get; set; }
        public System.DateTime datetime_start { get; set; }
        public System.DateTime datetime_stop { get; set; }
        public double losstime_second { get; set; }
        public Nullable<double> manpower { get; set; }
        public double total_second { get; set; }
        public string partnumber_start { get; set; }
        public string partnumber_stop { get; set; }
        public string machine_id { get; set; }
        public string fault_code { get; set; }
        public string machine_stop { get; set; }
        public Nullable<double> pure_loss { get; set; }
    }
}
