//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class xOEE_MC
    {
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public string machineID { get; set; }
        public double LoadingTime { get; set; }
        public double A1 { get; set; }
        public double A2 { get; set; }
        public double A3 { get; set; }
        public double P1 { get; set; }
        public double P2 { get; set; }
        public double P3 { get; set; }
        public double P4 { get; set; }
        public double OK { get; set; }
        public double NG { get; set; }
        public double RE { get; set; }
        public double A { get; set; }
        public double P { get; set; }
        public double Q { get; set; }
        public double OEE { get; set; }
    }
}
