//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class xOEE_Line
    {
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public double A { get; set; }
        public double P { get; set; }
        public double Q { get; set; }
        public double OEE { get; set; }
    }
}
