//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class xoeeLine
    {
        public string section_id { get; set; }
        public System.DateTime regist_date { get; set; }
        public double availability { get; set; }
        public double performance { get; set; }
        public double quality { get; set; }
        public double oee_summary { get; set; }
        public Nullable<double> oee_denso { get; set; }
    }
}
