//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OABoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_SectionTable
    {
        public string sectionCode { get; set; }
        public string sectionName { get; set; }
        public string divisionID { get; set; }
        public string plantID { get; set; }
    }
}
