//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OABoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class OR_log
    {
        public int run { get; set; }
        public string sectionCode { get; set; }
        public System.DateTime registDate { get; set; }
        public System.DateTime registDateTime { get; set; }
        public double ctAvg { get; set; }
        public double ctWeight { get; set; }
        public double orAvg { get; set; }
        public double orWeight { get; set; }
    }
}
