//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OABoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_NetTimeTable
    {
        public int run { get; set; }
        public string registYear { get; set; }
        public string sectionCode { get; set; }
        public string partNumber { get; set; }
        public double netTime { get; set; }
        public double CT { get; set; }
    }
}
